config/routes.rb
Rails.application.routes.draw do 

  root 'blog#home'
  devise_for :users 
  devise_scope :user do
    get '/users/:id/display-all' => "users#display_all", as: :display_all
  end

  resources :posts do
    resources :comments, only: [:create]
  end

  get 'topic/:slug' => 'posts#show',                     as: :topic

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates  :title,   presence: true
  validates  :body,    presence: true, length: { maximum: 340 }
  validates  :user_id, presence: true
  validates  :post_id, presence: true
  default_scope -> { order(created_at: :desc) }

  def to_s
    title
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many  :comments, dependent: :destroy
  validates  :title,   presence: true
  validates  :body,    presence: true
  validates  :user_id, presence: true
  validates  :slug,    presence: true, uniqueness: true
  default_scope -> { order(created_at: :desc) }
  before_validation :set_slug

  def to_s
    title
  end
  
  private
    def set_slug
      self.slug = [Random.rand(100), self.title.parameterize].join("-")
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :trackable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :recoverable

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :username, presence: true, length: { maximum: 60 },
                       uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :comments

  def to_s
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def home
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:user).paginate(page: params[:page], :per_page => 20)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    if (params[:slug])
      @post = Post.includes(:user).find_by( slug: params[:slug])
    else
      @post = Post.includes(:user).find(params[:id])
    end
    @comments = @post.comments.includes(:user).paginate(page: params[:page], :per_page => 10)
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    authorize @post
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def display_all
    @user = User.includes(:posts, :comments).find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def topic_slug_path post
    topic_path(post.slug)
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/home.html.haml
= provide(:title, 'Home')
%h1 Sample Blog
%p This is sample blog app

app/views/comments/_comment.html.haml
= div_for comment do
  %p
    %b= h(comment.title)
    %i
      Posted #{time_ago_in_words(comment.created_at)} 
      by #{link_to comment.user, display_all_path(comment.user)}
    %br
    = h(comment.body)

app/views/comments/_form.html.haml
= form_for([@post, Comment.new], remote: true) do |f|
  %p
    = f.label :title
    %br/
    = f.text_area :title
  %p
    = f.label :body, "New Comment"
    %br/
    = f.text_area :body
  %p
    = f.submit "Add Comment"

app/views/comments/create.js.haml
var new_comment = $("#{ escape_javascript(render(:partial => @comment)) }").hide();
$("#comments").prepend(new_comment);
$("#comment_#{ @comment.id }").fadeIn('slow');
$("new_comment")[0].reset();

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => "#myNavbar", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'SampleBlog', root_path, class: 'navbar-brand'
    #myNavbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'Home', root_path
      %ul.nav.navbar-nav
        %li
          = link_to 'Posts', posts_path
      %ul.nav.navbar-nav.navbar-right
        - unless user_signed_in?
          %li
            = link_to new_user_registration_path do
              %span.glyphicon.glyphicon-user
              Sign Up
          
          %li
            = link_to new_user_session_path do
              %span.glyphicon.glyphicon-log-in
              Login
        - else
          %li
            = link_to destroy_user_session_path, :method => :delete do
              %span.glyphicon.glyphicon-log-in
              Logout

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= yield(:title) 
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/posts/_post.html.haml
%tr
  %td= link_to post.title, topic_slug_path(post)
  %td By #{link_to post.user, display_all_path(post.user)}
  - if policy(post).owner?
    %td= link_to 'Edit', edit_post_path(post)
    %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
= provide(:title, "Posts")
%h1 Posts

- if user_signed_in?
  = link_to new_post_path do
    %span.glyphicon.glyphicon-plus
    Add Post
    
%table

  %tbody
    = render @posts
      
%br

= will_paginate @posts, renderer: BootstrapPagination::Rails 

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b= @post.title 
  %i By #{link_to @post.user, display_all_path(@post.user)}
%p
  %p= @post.body


= link_to 'Back', posts_path

%h2 Comments
#comments
  = render :partial => @comments
  = will_paginate @comments, renderer: BootstrapPagination::Rails
-if user_signed_in?
  = render 'comments/form'

app/views/users/display_all.html.haml
%h3 User all Posts
- @user.posts.each do |post|
  %p= link_to post, topic_slug_path(post)

%h3 User all comments
- @user.comments.each do |comment|
  %p 
    #{comment.title} #{time_ago_in_words(comment.created_at)} 